# Generated by Django 4.2.10 on 2024-02-15 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='dateOfTodo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
